-- SAIF / LSIF Dev v0.26A.1.29
-- Controlled 12 Savehouse Garage Catalog Apply Foundation
-- SAFETY: tracking/archive schema only. Does not insert garage_catalog or house_garage_links rows.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS garage_catalog_runtime_archive_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    archive_version VARCHAR(80) NOT NULL,
    geometry_session_id BIGINT UNSIGNED NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'building',
    runtime_rows_total INT UNSIGNED NOT NULL DEFAULT 0,
    active_rows_total INT UNSIGNED NOT NULL DEFAULT 0,
    link_rows_total INT UNSIGNED NOT NULL DEFAULT 0,
    active_link_rows_total INT UNSIGNED NOT NULL DEFAULT 0,
    policy_key VARCHAR(64) NOT NULL DEFAULT '',
    policy_enabled TINYINT(1) NOT NULL DEFAULT 0,
    policy_max_catalog_rows SMALLINT UNSIGNED NOT NULL DEFAULT 64,
    policy_interaction_radius DECIMAL(8,2) NOT NULL DEFAULT 5.00,
    policy_vehicle_required TINYINT(1) NOT NULL DEFAULT 1,
    policy_inherit_house_owner TINYINT(1) NOT NULL DEFAULT 1,
    policy_store_enabled TINYINT(1) NOT NULL DEFAULT 0,
    policy_retrieve_enabled TINYINT(1) NOT NULL DEFAULT 0,
    policy_door_animation_enabled TINYINT(1) NOT NULL DEFAULT 0,
    notes VARCHAR(768) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_garage_archive_version_status (archive_version,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS garage_catalog_runtime_archive_rows (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    archive_session_id BIGINT UNSIGNED NOT NULL,
    original_id BIGINT UNSIGNED NOT NULL,
    canonical_garage_plan_id BIGINT UNSIGNED NULL,
    source_queue_id BIGINT UNSIGNED NOT NULL,
    garage_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    garage_name VARCHAR(40) NOT NULL,
    runtime_class VARCHAR(40) NOT NULL,
    safety_class VARCHAR(48) NOT NULL,
    garage_type INT NOT NULL,
    garage_door_type INT NOT NULL,
    center_x FLOAT NOT NULL,
    center_y FLOAT NOT NULL,
    center_z FLOAT NOT NULL,
    bound_x1 FLOAT NOT NULL,
    bound_y1 FLOAT NOT NULL,
    bound_z1 FLOAT NOT NULL,
    bound_x2 FLOAT NOT NULL,
    bound_y2 FLOAT NOT NULL,
    bound_x3 FLOAT NOT NULL,
    bound_y3 FLOAT NOT NULL,
    bound_z2 FLOAT NOT NULL,
    interaction_x FLOAT NOT NULL,
    interaction_y FLOAT NOT NULL,
    interaction_z FLOAT NOT NULL,
    vehicle_spawn_x FLOAT NULL,
    vehicle_spawn_y FLOAT NULL,
    vehicle_spawn_z FLOAT NULL,
    vehicle_spawn_a FLOAT NULL,
    spawn_status VARCHAR(24) NOT NULL,
    source_file VARCHAR(512) NOT NULL,
    source_line INT UNSIGNED NOT NULL,
    source_record_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    city_region VARCHAR(32) NOT NULL,
    area_code VARCHAR(32) NOT NULL,
    enabled TINYINT(1) NOT NULL,
    apply_status VARCHAR(24) NOT NULL,
    sort_order INT NOT NULL,
    source_tag VARCHAR(64) NOT NULL,
    row_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    original_created_at TIMESTAMP NULL,
    original_updated_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_garage_archive_row (archive_session_id,original_id),
    KEY idx_garage_archive_source (archive_session_id,source_queue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS garage_house_link_runtime_archive_rows (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    archive_session_id BIGINT UNSIGNED NOT NULL,
    original_id BIGINT UNSIGNED NOT NULL,
    house_catalog_id BIGINT UNSIGNED NOT NULL,
    garage_catalog_id BIGINT UNSIGNED NOT NULL,
    canonical_house_slot INT NULL,
    link_class VARCHAR(48) NOT NULL,
    ownership_mode VARCHAR(32) NOT NULL,
    access_mode VARCHAR(32) NOT NULL,
    enabled TINYINT(1) NOT NULL,
    source_tag VARCHAR(64) NOT NULL,
    original_created_at TIMESTAMP NULL,
    original_updated_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_garage_link_archive_row (archive_session_id,original_id),
    KEY idx_garage_link_archive_house (archive_session_id,house_catalog_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS garage_catalog_apply_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    apply_version VARCHAR(80) NOT NULL,
    archive_session_id BIGINT UNSIGNED NOT NULL,
    geometry_session_id BIGINT UNSIGNED NOT NULL,
    garage_resolver_session_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'applying',
    expected_catalog_rows INT UNSIGNED NOT NULL DEFAULT 12,
    expected_link_rows INT UNSIGNED NOT NULL DEFAULT 12,
    applied_catalog_rows INT UNSIGNED NOT NULL DEFAULT 0,
    applied_link_rows INT UNSIGNED NOT NULL DEFAULT 0,
    policy_enabled_after TINYINT(1) NOT NULL DEFAULT 0,
    policy_store_enabled_after TINYINT(1) NOT NULL DEFAULT 0,
    policy_retrieve_enabled_after TINYINT(1) NOT NULL DEFAULT 0,
    policy_door_enabled_after TINYINT(1) NOT NULL DEFAULT 0,
    notes VARCHAR(768) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    rolled_back_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_garage_apply_version_status (apply_version,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS garage_catalog_apply_rows (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    apply_session_id BIGINT UNSIGNED NOT NULL,
    geometry_plan_id BIGINT UNSIGNED NOT NULL,
    garage_plan_id BIGINT UNSIGNED NOT NULL,
    house_plan_id BIGINT UNSIGNED NOT NULL,
    house_catalog_id BIGINT UNSIGNED NOT NULL,
    garage_catalog_id BIGINT UNSIGNED NOT NULL,
    house_garage_link_id BIGINT UNSIGNED NOT NULL,
    canonical_house_slot INT NOT NULL,
    source_queue_id BIGINT UNSIGNED NOT NULL,
    garage_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    garage_name VARCHAR(40) NOT NULL,
    geometry_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    catalog_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    link_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    row_status VARCHAR(24) NOT NULL DEFAULT 'applied',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_garage_apply_geometry (apply_session_id,geometry_plan_id),
    UNIQUE KEY uq_garage_apply_catalog (apply_session_id,garage_catalog_id),
    UNIQUE KEY uq_garage_apply_link (apply_session_id,house_garage_link_id),
    KEY idx_garage_apply_house (apply_session_id,house_catalog_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'CONTROLLED_12_GARAGE_APPLY_SCHEMA' section,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='garage_catalog_runtime_archive_sessions') archive_sessions_table_should_be_1,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='garage_catalog_runtime_archive_rows') archive_rows_table_should_be_1,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='garage_house_link_runtime_archive_rows') archive_links_table_should_be_1,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='garage_catalog_apply_sessions') apply_sessions_table_should_be_1,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='garage_catalog_apply_rows') apply_rows_table_should_be_1;
