-- SAIF / LSIF Dev v0.26A.1.21
-- GTA SA House, Savehouse & Property Source Queue Foundation
-- SAFETY: staging/audit tables only. No player_houses, houses, public_interiors, world_pickups, or garage runtime mutation.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_property_source_sessions (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 session_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
 parser_version VARCHAR(72) NOT NULL,
 source_version VARCHAR(64) NOT NULL DEFAULT 'GTA SA PC 1.0 US',
 status VARCHAR(24) NOT NULL DEFAULT 'building',
 total_rows INT UNSIGNED NOT NULL DEFAULT 0,
 property_for_sale_rows INT UNSIGNED NOT NULL DEFAULT 0,
 property_locked_rows INT UNSIGNED NOT NULL DEFAULT 0,
 savegame_rows INT UNSIGNED NOT NULL DEFAULT 0,
 enex_savehouse_rows INT UNSIGNED NOT NULL DEFAULT 0,
 enex_property_rows INT UNSIGNED NOT NULL DEFAULT 0,
 garage_rows INT UNSIGNED NOT NULL DEFAULT 0,
 unique_property_slots INT UNSIGNED NOT NULL DEFAULT 0,
 unique_save_positions INT UNSIGNED NOT NULL DEFAULT 0,
 duplicate_extra_rows INT UNSIGNED NOT NULL DEFAULT 0,
 notes VARCHAR(512) NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMP NULL DEFAULT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uq_offline_property_source_session_key(session_key),
 KEY idx_offline_property_source_session_parser(parser_version,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_property_source_queue (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 session_id BIGINT UNSIGNED NOT NULL,
 parser_version VARCHAR(72) NOT NULL,
 source_tag VARCHAR(64) NOT NULL DEFAULT 'offline_gtasa_property_source',
 evidence_type VARCHAR(48) NOT NULL,
 source_scope VARCHAR(24) NOT NULL,
 source_file VARCHAR(512) NOT NULL,
 source_line INT UNSIGNED NOT NULL DEFAULT 0,
 record_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
 source_command VARCHAR(48) NOT NULL DEFAULT '',
 handle_name VARCHAR(128) NOT NULL DEFAULT '',
 script_name VARCHAR(64) NOT NULL DEFAULT '',
 script_label VARCHAR(128) NOT NULL DEFAULT '',
 slot_index INT NOT NULL DEFAULT -1,
 state_hint VARCHAR(48) NOT NULL DEFAULT 'reference_only',
 price_token VARCHAR(64) NOT NULL DEFAULT '',
 price_value INT NULL,
 raw_name VARCHAR(96) NOT NULL DEFAULT '',
 display_name VARCHAR(160) NOT NULL DEFAULT '',
 context_type VARCHAR(48) NOT NULL DEFAULT 'unknown',
 confidence TINYINT UNSIGNED NOT NULL DEFAULT 0,
 position_x FLOAT NOT NULL DEFAULT 0,
 position_y FLOAT NOT NULL DEFAULT 0,
 position_z FLOAT NOT NULL DEFAULT 0,
 position_a FLOAT NOT NULL DEFAULT 0,
 position_resolved TINYINT(1) NOT NULL DEFAULT 0,
 interior_id INT NOT NULL DEFAULT 0,
 exit_x FLOAT NOT NULL DEFAULT 0,
 exit_y FLOAT NOT NULL DEFAULT 0,
 exit_z FLOAT NOT NULL DEFAULT 0,
 exit_a FLOAT NOT NULL DEFAULT 0,
 garage_name VARCHAR(32) NOT NULL DEFAULT '',
 garage_type INT NOT NULL DEFAULT -1,
 garage_door_type INT NOT NULL DEFAULT -1,
 bounds_json TEXT NULL,
 city_region VARCHAR(32) NOT NULL DEFAULT '',
 area_code VARCHAR(32) NOT NULL DEFAULT '',
 duplicate_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
 duplicate_group_size SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 apply_status VARCHAR(24) NOT NULL DEFAULT 'pending',
 notes VARCHAR(255) NOT NULL DEFAULT '',
 raw_record TEXT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),
 UNIQUE KEY uq_offline_property_source_hash(session_id,record_hash),
 KEY idx_offline_property_source_type(evidence_type,state_hint),
 KEY idx_offline_property_source_slot(slot_index,evidence_type),
 KEY idx_offline_property_source_context(context_type,city_region,area_code),
 KEY idx_offline_property_source_apply(enabled,apply_status),
 KEY idx_offline_property_source_duplicate(duplicate_key),
 CONSTRAINT fk_offline_property_source_session FOREIGN KEY(session_id) REFERENCES offline_property_source_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
