-- SAIF / LSIF Dev v0.26A.1.22
-- House / Property Canonical Resolver & Pair Planner
-- SAFETY: staging plan only. No player_houses or runtime mutation.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_property_resolver_sessions (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 source_session_id BIGINT UNSIGNED NOT NULL,
 resolver_version VARCHAR(72) NOT NULL,
 source_parser_version VARCHAR(72) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'building',
 total_plans INT UNSIGNED NOT NULL DEFAULT 0,
 baseline_ready_rows INT UNSIGNED NOT NULL DEFAULT 0,
 deferred_rows INT UNSIGNED NOT NULL DEFAULT 0,
 exact_pair_rows INT UNSIGNED NOT NULL DEFAULT 0,
 unpaired_asset_rows INT UNSIGNED NOT NULL DEFAULT 0,
 savepoint_linked_rows INT UNSIGNED NOT NULL DEFAULT 0,
 garage_candidate_rows INT UNSIGNED NOT NULL DEFAULT 0,
 notes VARCHAR(768) NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMP NULL DEFAULT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uq_offline_property_resolver(source_session_id,resolver_version),
 KEY idx_offline_property_resolver_status(resolver_version,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_property_canonical_plan (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 resolver_session_id BIGINT UNSIGNED NOT NULL,
 source_session_id BIGINT UNSIGNED NOT NULL,
 resolver_version VARCHAR(72) NOT NULL,
 plan_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
 slot_index INT NOT NULL,
 display_name VARCHAR(160) NOT NULL,
 asset_class VARCHAR(64) NOT NULL,
 decision_code VARCHAR(48) NOT NULL,
 safety_class VARCHAR(64) NOT NULL,
 runtime_target VARCHAR(64) NOT NULL,
 for_sale_queue_id BIGINT UNSIGNED NOT NULL,
 locked_queue_id BIGINT UNSIGNED NULL,
 exterior_enex_queue_id BIGINT UNSIGNED NULL,
 interior_enex_queue_id BIGINT UNSIGNED NULL,
 savegame_queue_id BIGINT UNSIGNED NULL,
 garage_queue_id BIGINT UNSIGNED NULL,
 price_value INT NOT NULL DEFAULT 0,
 purchase_x FLOAT NOT NULL DEFAULT 0,
 purchase_y FLOAT NOT NULL DEFAULT 0,
 purchase_z FLOAT NOT NULL DEFAULT 0,
 purchase_a FLOAT NOT NULL DEFAULT 0,
 city_region VARCHAR(32) NOT NULL DEFAULT '',
 area_code VARCHAR(32) NOT NULL DEFAULT '',
 pair_group_key VARCHAR(96) NOT NULL DEFAULT '',
 pair_status VARCHAR(32) NOT NULL,
 pair_distance FLOAT NULL,
 exterior_x FLOAT NOT NULL DEFAULT 0,
 exterior_y FLOAT NOT NULL DEFAULT 0,
 exterior_z FLOAT NOT NULL DEFAULT 0,
 exterior_a FLOAT NOT NULL DEFAULT 0,
 exterior_spawn_x FLOAT NOT NULL DEFAULT 0,
 exterior_spawn_y FLOAT NOT NULL DEFAULT 0,
 exterior_spawn_z FLOAT NOT NULL DEFAULT 0,
 exterior_spawn_a FLOAT NOT NULL DEFAULT 0,
 interior_id INT NOT NULL DEFAULT 0,
 interior_exit_x FLOAT NOT NULL DEFAULT 0,
 interior_exit_y FLOAT NOT NULL DEFAULT 0,
 interior_exit_z FLOAT NOT NULL DEFAULT 0,
 interior_exit_a FLOAT NOT NULL DEFAULT 0,
 interior_spawn_x FLOAT NOT NULL DEFAULT 0,
 interior_spawn_y FLOAT NOT NULL DEFAULT 0,
 interior_spawn_z FLOAT NOT NULL DEFAULT 0,
 interior_spawn_a FLOAT NOT NULL DEFAULT 0,
 savepoint_status VARCHAR(32) NOT NULL DEFAULT 'not_linked',
 savepoint_x FLOAT NOT NULL DEFAULT 0,
 savepoint_y FLOAT NOT NULL DEFAULT 0,
 savepoint_z FLOAT NOT NULL DEFAULT 0,
 savepoint_distance FLOAT NULL,
 garage_status VARCHAR(32) NOT NULL DEFAULT 'none',
 garage_name VARCHAR(32) NOT NULL DEFAULT '',
 garage_type INT NOT NULL DEFAULT -1,
 garage_distance FLOAT NULL,
 private_vw_required TINYINT(1) NOT NULL DEFAULT 0,
 confidence TINYINT UNSIGNED NOT NULL DEFAULT 0,
 resolver_reason VARCHAR(1024) NOT NULL DEFAULT '',
 source_tag VARCHAR(64) NOT NULL DEFAULT 'offline_gtasa_house_plan',
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 apply_status VARCHAR(24) NOT NULL DEFAULT 'draft',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),
 UNIQUE KEY uq_offline_property_plan_key(plan_key),
 UNIQUE KEY uq_offline_property_plan_slot(resolver_session_id,slot_index),
 KEY idx_offline_property_plan_decision(resolver_version,decision_code),
 KEY idx_offline_property_plan_runtime(runtime_target,apply_status),
 CONSTRAINT fk_offline_property_plan_resolver FOREIGN KEY(resolver_session_id) REFERENCES offline_property_resolver_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
