-- SAIF / LSIF Dev v0.26A.1.28
-- Garage Vehicle Spawn & Interaction Geometry Planner
-- SAFETY: staging/planner schema only. No garage_catalog, house_garage_links, vehicles, doors, checkpoints, house ownership, or runtime world mutation.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_garage_geometry_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    garage_resolver_session_id BIGINT UNSIGNED NOT NULL,
    planner_version VARCHAR(80) NOT NULL,
    source_resolver_version VARCHAR(80) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'building',
    total_rows INT UNSIGNED NOT NULL DEFAULT 0,
    baseline_rows INT UNSIGNED NOT NULL DEFAULT 0,
    baseline_ready_rows INT UNSIGNED NOT NULL DEFAULT 0,
    story_rows INT UNSIGNED NOT NULL DEFAULT 0,
    service_rows INT UNSIGNED NOT NULL DEFAULT 0,
    world_reference_rows INT UNSIGNED NOT NULL DEFAULT 0,
    invalid_bounds INT UNSIGNED NOT NULL DEFAULT 0,
    invalid_dimensions INT UNSIGNED NOT NULL DEFAULT 0,
    invalid_spawn INT UNSIGNED NOT NULL DEFAULT 0,
    notes VARCHAR(768) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_offline_garage_geometry_session (planner_version,garage_resolver_session_id),
    KEY idx_offline_garage_geometry_status (planner_version,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_garage_geometry_plan (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    geometry_session_id BIGINT UNSIGNED NOT NULL,
    garage_plan_id BIGINT UNSIGNED NOT NULL,
    source_queue_id BIGINT UNSIGNED NOT NULL,
    garage_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    garage_name VARCHAR(40) NOT NULL,
    runtime_class VARCHAR(40) NOT NULL,
    safety_class VARCHAR(48) NOT NULL,
    point1_x FLOAT NOT NULL DEFAULT 0,
    point1_y FLOAT NOT NULL DEFAULT 0,
    floor_z FLOAT NOT NULL DEFAULT 0,
    point2_x FLOAT NOT NULL DEFAULT 0,
    point2_y FLOAT NOT NULL DEFAULT 0,
    point3_x FLOAT NOT NULL DEFAULT 0,
    point3_y FLOAT NOT NULL DEFAULT 0,
    ceiling_z FLOAT NOT NULL DEFAULT 0,
    front_width FLOAT NOT NULL DEFAULT 0,
    depth_length FLOAT NOT NULL DEFAULT 0,
    height_clearance FLOAT NOT NULL DEFAULT 0,
    depth_unit_x FLOAT NOT NULL DEFAULT 0,
    depth_unit_y FLOAT NOT NULL DEFAULT 0,
    front_mid_x FLOAT NOT NULL DEFAULT 0,
    front_mid_y FLOAT NOT NULL DEFAULT 0,
    front_mid_z FLOAT NOT NULL DEFAULT 0,
    interaction_x FLOAT NOT NULL DEFAULT 0,
    interaction_y FLOAT NOT NULL DEFAULT 0,
    interaction_z FLOAT NOT NULL DEFAULT 0,
    vehicle_entry_x FLOAT NOT NULL DEFAULT 0,
    vehicle_entry_y FLOAT NOT NULL DEFAULT 0,
    vehicle_entry_z FLOAT NOT NULL DEFAULT 0,
    vehicle_entry_a FLOAT NOT NULL DEFAULT 0,
    vehicle_spawn_x FLOAT NOT NULL DEFAULT 0,
    vehicle_spawn_y FLOAT NOT NULL DEFAULT 0,
    vehicle_spawn_z FLOAT NOT NULL DEFAULT 0,
    vehicle_spawn_a FLOAT NOT NULL DEFAULT 0,
    checkpoint_radius FLOAT NOT NULL DEFAULT 2.5,
    geometry_status VARCHAR(32) NOT NULL DEFAULT 'unresolved',
    review_reason VARCHAR(512) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    apply_status VARCHAR(24) NOT NULL DEFAULT 'draft',
    row_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_offline_garage_geometry_plan (geometry_session_id,garage_plan_id),
    UNIQUE KEY uq_offline_garage_geometry_source (geometry_session_id,source_queue_id),
    KEY idx_offline_garage_geometry_class (geometry_session_id,safety_class,geometry_status),
    KEY idx_offline_garage_geometry_apply (enabled,apply_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'GARAGE_GEOMETRY_SCHEMA' section,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='offline_garage_geometry_sessions') sessions_table_should_be_1,
       (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='offline_garage_geometry_plan') plan_table_should_be_1;
