-- SAIF / LSIF Dev v0.26A.1.17
-- GTA SA Offline Pickup Queue Foundation
-- SAFETY: staging/audit tables only. No world_pickups runtime mutation.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_pickup_queue (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 session_id BIGINT UNSIGNED NOT NULL,
 source_file_id BIGINT UNSIGNED NULL,
 source_scope VARCHAR(16) NOT NULL DEFAULT 'SCM',
 source_file VARCHAR(512) NOT NULL,
 source_line INT UNSIGNED NOT NULL DEFAULT 0,
 record_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
 parser_version VARCHAR(64) NOT NULL DEFAULT 'saif-pickup-parser-v0.26A.1.17',
 source_tag VARCHAR(64) NOT NULL DEFAULT 'offline_gtasa_pickup_queue',
 source_command VARCHAR(48) NOT NULL,
 handle_name VARCHAR(128) NOT NULL DEFAULT '',
 script_name VARCHAR(64) NOT NULL DEFAULT '',
 script_label VARCHAR(128) NOT NULL DEFAULT '',
 model_token VARCHAR(64) NOT NULL DEFAULT '',
 model_id INT NULL,
 model_resolution VARCHAR(32) NOT NULL DEFAULT 'not_applicable',
 weapon_id_guess INT NOT NULL DEFAULT 0,
 pickup_type_token VARCHAR(64) NOT NULL DEFAULT '',
 pickup_category VARCHAR(48) NOT NULL DEFAULT 'unknown',
 context_category VARCHAR(48) NOT NULL DEFAULT 'world_reference',
 multiplayer_safety VARCHAR(48) NOT NULL DEFAULT 'review_required',
 ammo_amount INT NULL,
 cash_amount INT NULL,
 property_price_token VARCHAR(64) NOT NULL DEFAULT '',
 property_price_value INT NULL,
 revenue_limit_token VARCHAR(64) NOT NULL DEFAULT '',
 revenue_limit_value INT NULL,
 revenue_rate_token VARCHAR(64) NOT NULL DEFAULT '',
 revenue_rate_value INT NULL,
 permanent_value TINYINT NULL,
 pos_x_token VARCHAR(64) NOT NULL DEFAULT '',
 pos_y_token VARCHAR(64) NOT NULL DEFAULT '',
 pos_z_token VARCHAR(64) NOT NULL DEFAULT '',
 pos_x FLOAT NOT NULL DEFAULT 0,
 pos_y FLOAT NOT NULL DEFAULT 0,
 pos_z FLOAT NOT NULL DEFAULT 0,
 position_resolved TINYINT(1) NOT NULL DEFAULT 0,
 resolution_mode VARCHAR(32) NOT NULL DEFAULT 'unresolved',
 zero_coordinate TINYINT(1) NOT NULL DEFAULT 0,
 city_region VARCHAR(32) NOT NULL DEFAULT '',
 area_code VARCHAR(32) NOT NULL DEFAULT '',
 duplicate_key CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
 duplicate_group_size SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 apply_status VARCHAR(24) NOT NULL DEFAULT 'pending',
 notes VARCHAR(255) NOT NULL DEFAULT '',
 raw_record TEXT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),
 UNIQUE KEY uq_offline_pickup_session_hash(session_id,record_hash),
 KEY idx_offline_pickup_parser(parser_version,source_scope),
 KEY idx_offline_pickup_category(pickup_category,multiplayer_safety),
 KEY idx_offline_pickup_position(position_resolved,zero_coordinate),
 KEY idx_offline_pickup_area(city_region,area_code),
 KEY idx_offline_pickup_apply(enabled,apply_status),
 KEY idx_offline_pickup_duplicate(duplicate_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
