-- SAIF / LSIF Dev v0.26A.1.7
-- ENEX Pair Audit & Apply Planner
-- SAFETY: staging/dry-run tables only. No public_interiors or other runtime table mutation.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_interior_apply_batches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    session_id BIGINT UNSIGNED NOT NULL,
    plan_version VARCHAR(64) NOT NULL,
    batch_key VARCHAR(64) NOT NULL,
    batch_label VARCHAR(128) NOT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    candidate_count INT UNSIGNED NOT NULL DEFAULT 0,
    pair_ready_count INT UNSIGNED NOT NULL DEFAULT 0,
    dry_run_ready_count INT UNSIGNED NOT NULL DEFAULT 0,
    service_pending_count INT UNSIGNED NOT NULL DEFAULT 0,
    blocked_count INT UNSIGNED NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    dry_run_only TINYINT(1) NOT NULL DEFAULT 1,
    notes VARCHAR(512) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_offline_apply_batch (session_id, plan_version, batch_key),
    KEY idx_offline_apply_batch_status (session_id, plan_version, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offline_interior_apply_plan (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    session_id BIGINT UNSIGNED NOT NULL,
    batch_id BIGINT UNSIGNED NOT NULL,
    plan_version VARCHAR(64) NOT NULL,
    plan_key CHAR(64) NOT NULL,
    context_type VARCHAR(64) NOT NULL,
    runtime_type VARCHAR(32) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    pair_group_key VARCHAR(96) NOT NULL,
    region_key VARCHAR(32) NOT NULL DEFAULT '',
    city_code VARCHAR(32) NOT NULL DEFAULT '',
    area_code VARCHAR(32) NOT NULL DEFAULT '',
    exterior_queue_id BIGINT UNSIGNED NOT NULL,
    interior_queue_id BIGINT UNSIGNED NOT NULL,
    exterior_record_hash CHAR(64) NOT NULL,
    interior_record_hash CHAR(64) NOT NULL,
    plan_status VARCHAR(24) NOT NULL DEFAULT 'pair_ready',
    service_point_status VARCHAR(32) NOT NULL DEFAULT 'exact_required',
    apply_readiness VARCHAR(32) NOT NULL DEFAULT 'service_point_pending',
    confidence TINYINT UNSIGNED NOT NULL DEFAULT 0,
    exterior_x FLOAT NOT NULL DEFAULT 0,
    exterior_y FLOAT NOT NULL DEFAULT 0,
    exterior_z FLOAT NOT NULL DEFAULT 0,
    exterior_a FLOAT NOT NULL DEFAULT 0,
    exterior_spawn_x FLOAT NOT NULL DEFAULT 0,
    exterior_spawn_y FLOAT NOT NULL DEFAULT 0,
    exterior_spawn_z FLOAT NOT NULL DEFAULT 0,
    exterior_spawn_a FLOAT NOT NULL DEFAULT 0,
    interior_id INT NOT NULL DEFAULT 0,
    interior_x FLOAT NOT NULL DEFAULT 0,
    interior_y FLOAT NOT NULL DEFAULT 0,
    interior_z FLOAT NOT NULL DEFAULT 0,
    interior_a FLOAT NOT NULL DEFAULT 0,
    exit_x FLOAT NOT NULL DEFAULT 0,
    exit_y FLOAT NOT NULL DEFAULT 0,
    exit_z FLOAT NOT NULL DEFAULT 0,
    exit_a FLOAT NOT NULL DEFAULT 0,
    duplicate_of_hash CHAR(64) NOT NULL DEFAULT '',
    planner_reason VARCHAR(768) NOT NULL DEFAULT '',
    source_tag VARCHAR(64) NOT NULL DEFAULT 'offline_enex_apply_plan',
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    apply_status VARCHAR(24) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_offline_apply_plan_key (plan_key),
    UNIQUE KEY uq_offline_apply_plan_exterior (session_id, plan_version, exterior_queue_id),
    KEY idx_offline_apply_plan_batch (batch_id, apply_readiness),
    KEY idx_offline_apply_plan_context (session_id, context_type),
    KEY idx_offline_apply_plan_region (session_id, region_key),
    KEY idx_offline_apply_plan_status (session_id, plan_status, apply_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
